open-ead/sead

CMakeLists.txt, modules/src/heap/seadExpHeap.cpp
Some stuffs I had in local for some time.
Was compared against botw's sead implementation.
=> expheap: Add isEmpty, isFreeable, isResizable and isAdjustable

include/devenv/seadEnvUtil.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-ead/sead/84)
=> Added RegionLanguageID/getRegionLanguage

CMakeLists.txt, include/gfx/seadDrawContext.h, include/gfx/seadFrameBuffer.h
This PR adds existing header files from the OdysseyReversed project by shibbo (https://github.com/shibbo/OdysseyReversed/tree/master/include/sead), which are necessary to merging PR#2 of the `agl`-project. (https://github.com/open-ead/agl/pull/2)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-ead/sead/90)
=> Add headers for `agl` from OdysseyReversed

include/math/seadVector.h, include/math/seadVector.hpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-ead/sead/91)
=> math: Fix friend functions and add Vec3 negate

include/gfx/seadTextWriter.h, include/math/seadMathCalcCommon.hpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-ead/sead/93)
=> Add seadTextWriter and fix compiler warning in mathCalcCommon

include/controller/seadControllerBase.h, include/gfx/seadTextWriter.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-ead/sead/94)
=> Change button bit flag type to BitFlag32 and add setCursorFromTopLeft to TextWriter

include/mc/seadWorkerMgr.h, include/time/seadTickSpan.h, modules/src/time/seadTickSpan.cpp
Seen in SMR pead.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-ead/sead/99)
=> time/TickSpan: Make interface more consistent and match original names

include/stream/seadBufferStream.h
BufferWriteStream extends WriteStream and takes in a WriteStream in its constructor.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-ead/sead/103)
=> Correct BufferWriteStream to use WriteStream

include/camera/seadPerspectiveProjection.h, include/gfx/seadProjection.h
Adding functions and member variables of Projection and PerspectiveProjection, telling from the debug symbols and information of Super Mario Odyssey.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-ead/sead/110)
=> Add PerspectiveProjection

include/gfx/seadTextWriter.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-ead/sead/109)
=> gfx/TextWriter: Add all listed functions to header

include/gfx/seadPrimitiveRenderer.h
Some of these changes also originate from the SuperMarioOdysseyOnline repository, but have been cleaned and improved with more knowledge from the binary, along with all listed functions added.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-ead/sead/108)
=> gfx/PrimitiveRenderer: Cleanup, better headers

include/gfx/seadGraphics.h, include/gfx/seadProjection.h, include/gfx/seadViewport.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-ead/sead/111)
=> gfx: Add Viewport header

include/container/seadTreeMap.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-ead/sead/114)
=> Add FixedTreeMap class

include/container/seadTreeMap.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-ead/sead/115)
=> Remove the destructor from TreeMap

modules/src/thread/nin/seadThreadNin.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-ead/sead/116)
=> thread/nin: Fix build issue after nn::gfx merge

include/framework/seadFramework.h, modules/src/framework/seadGameFramework.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-ead/sead/117)
=> Fix warnings

include/gfx/seadProjection.h
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-ead/sead/121)
=> Remove pure virtual from updateAttributesForDirectProjection

include/devenv/seadFontMgr.h, include/gfx/nin/seadGraphicsNvn.h, include/gfx/seadGraphics.h, modules/src/devenv/seadFontMgr.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-ead/sead/125)
=> DebugFontMgrJis1Nvn::initializeFromBinary

modules/src/math/seadQuat.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-ead/sead/127)
=> math: fix sead::Quat<float>::unit

include/gfx/seadTextWriter.h
Adding more details I found in a random discord message containing a header created by @shadowninja108 .
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-ead/sead/147)
=> gfx: Improve `seadTextWriter`

include/gfx/seadProjection.h
Yeah, thats it. It is included in the 2 year old pull request, but I (kinda) need it.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-ead/sead/155)
=> Small additions in gfx/seadProjection.h

include/math/seadQuatCalcCommon.h, include/math/seadQuatCalcCommon.hpp
This PR fix `QuatCalcCommon::makeUnit`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-ead/sead/150)
=> Math/Quat: Fix `QuatCalcCommon::makeUnit`

include/gfx/seadCamera.h, include/math/seadVector.h, include/math/seadVector.hpp, include/math/seadVectorCalcCommon.h, include/math/seadVectorCalcCommon.hpp
I changed it up, otherwise my code in SMO would not match (CameraPoser)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-ead/sead/158)
=> gfx/Camera setters and math/Vector::negate

include/container/seadStrTreeMap.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-ead/sead/163)
=> container: Add `StrTreeMap::isBufferReady`

include/controller/seadControllerDefine.h
got these from `al::PadGyroAddon` and `al::PadUiKeyInputAddon` in SMO
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-ead/sead/166)
=> `controller`: add two entries to `ControllerDefine::AddonId`

include/framework/nx/seadGameFrameworkNx.h, include/framework/seadGameFramework.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-ead/sead/165)
=> `framework`: fill out more of `GameFrameworkNx.h`

include/controller/seadControllerDefine.h
similarly to #166 i got these from SMO, can all be found pretty easily from `al::GameFrameworkNx::createControllerMgr`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-ead/sead/172)
=> `controller/seadControllerDefine.h`: update `DeviceId` and `ControllerId` enums

include/gfx/seadProjection.h
forgot to check for compiler errors in this header; i've fixed them here.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-ead/sead/180)
=> gfx: fix seadProjection errors

include/math/seadMatrix.hpp
Is always fun when your code no longer works.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-ead/sead/187)
=> Math: Fix compiler errors introduced in 186

include/prim/seadSafeString.h, include/prim/seadSafeString.hpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-ead/sead/188)
=> prim: fix `BufferedSafeStringBase<T>::append(T)`

include/controller/nin/seadNinJoyNpadDevice.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-ead/sead/183)
=> `controller/nin`: fill out `seadNinJoyNpadDevice.h`

CMakeLists.txt, include/controller/seadControllerMgr.h, include/framework/seadTaskMgr.h, modules/src/controller/seadControllerMgr.cpp, modules/src/framework/seadGameFramework.cpp, modules/src/framework/seadTaskMgr.cpp
A while ago, we apparently removed this file from the `CMakeLists` due to heavy mismatches/compiler errors. In this PR, I added it back, fixed all related compiler errors and also some follow-up errors across other classes using the `TaskMgr` or some of its members.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-ead/sead/205)
=> framework: Fix `TaskMgr`
