- include/container/seadPtrArray.h
- include/filedevice/nin/seadNinSDFileDeviceNin.h
- include/prim/seadPtrUtil.h
- include/resource/seadDecompressor.h
- modules/src/resource/seadSharcArchiveRes.cpp
To support `clang-3.9.1` for building Super Mario Odyssey, `C++17` features have to be dropped. Here, this results in one major change:
As `string_view` gets unusable, the signatures of blocks in `modules/src/resource/seadSharcArchiveRes.cpp` can't be checked using that. Instead, `std::strncmp` is used then.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-ead/sead/82)
> C++14 support (replacing C++17-only features)

- include/prim/seadEnum.h
As there is no macro for `SEAD_ENUM_IMPL` and it is not required, the comment removed in this PR is not only wrong, but also misleading.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-ead/sead/83)
> prim/Enum: Remove wrong comment

- include/controller/seadController.h
- include/controller/seadControllerBase.h
- include/controller/seadControllerMgr.h
- include/framework/seadTaskMgr.h
This PR adds some part of the input-related stuff into the decomp. These are the "frontend-classes", so the ones that games will most likely interact with. `SMO` uses another bunch of utility functions to read specific bits from the `seadControllerBase->mButtonTrigger`/... fields, so probably there is a similar system in place for other games too.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-ead/sead/89)
> controller: Add `seadController`, `Base` and `Mgr`

- include/math/seadMatrixCalcCommon.hpp
Matrix34CalcCommon<f32>::copy() can access FP/SIMD registers on aarch64
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-ead/sead/92)
> Matrix34CalcCommon<f32>::copy() can access FP/SIMD registers

- include/math/seadMatrix.h
- include/math/seadMatrix.hpp
- include/math/seadMatrixCalcCommon.h
- include/math/seadMatrixCalcCommon.hpp
- include/math/seadQuat.h
- include/math/seadQuat.hpp
- include/math/seadQuatCalcCommon.h
- include/math/seadQuatCalcCommon.hpp
Both are used by Super Mario Odyssey in the `ActorPoseKeeper` classes.
Maybe the `setRPY` function is a `Quatf`-specific one and should not be generalized to all types?
Example usages:
`makeQT`:
```cpp
void ActorPoseKeeperTQSV::calcBaseMtx(sead::Matrix34f* mtx) const {
mtx->makeQT(mQuat, mTrans);
}
```
`setRPY`:
```cpp
void ActorPoseKeeperBase::updatePoseRotate(const sead::Vector3f& rot) {
sead::Quatf quat;
quat.setRPY(sead::Mathf::deg2rad(rot.x), sead::Mathf::deg2rad(rot.y), sead::Mathf::deg2rad(rot.z));
updatePoseQuat(quat);
}
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-ead/sead/95)
> math: Add `makeQT` to Matrix and `setRPY` to Quat

- modules/src/thread/nin/seadEventNin.cpp
Due to recent changes in the `NintendoSDK`-headers, one function definition has been changed that is used locally, resulting in compile errors.
https://github.com/open-ead/sead/tree/8cb5a828b9def35496fc91bfdd3390ca64d247fb/modules/src/thread/nin/seadEventNin.cpp#L44
Tries to call nn::os::InitializeLightEvent with two boolean parameters (2nd and 3rd parameter), but
https://github.com/open-ead/nnheaders/blob/b15fa31fd4508590bad50473da9fd922a1e7e009/include/nn/os.h#L197
Accepts one boolean and one EventClearMode instead.
This PR fixes this, by adding a ternary to the call to call the function with the two possible values of `EventClearMode` instead.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
> `thread/nin`: Fix EventNin/ n::os::LightEvent-call

- include/math/seadMathCalcCommon.h
- include/math/seadMatrix.h
- include/math/seadMatrix.hpp
- include/math/seadMatrixCalcCommon.h
- include/math/seadMatrixCalcCommon.hpp
- include/math/seadQuat.h
- include/math/seadQuat.hpp
- include/math/seadQuatCalcCommon.h
The simplest change, `fitSign`, should be pretty straight-forward. To match the sign, it has to be properly removed before added again, which was missing previously. I don't have a function to test this.
Next, Matrix34->getRotation has been added, along with a fix for `makeRT` (constructing it from Rotation and Translation).
Finally, the "problematic" change, is adding `calcRPY` to `seadQuat`. This function is not inlined in Super Mario Odyssey, so I created a playground for this mismatch: https://decomp.me/scratch/jlIf0
It seems related to creating a Matrix from `makeQT`, followed by a `getRotation`, but using a real matrix in this context is not possible, and the `makeQT`-part seems to be slightly different.
---
This change is [<img src="https://reviewable.io/review_button.svg" …
> `math`: Improvements on `Matrix34` and `Quat`

- include/math/seadMathBase.h
- include/math/seadMatrix.h
- include/math/seadMatrix.hpp
Only for Matrix34 at the moment, we can add it for Matrix33 and Matrix44 if we see them used.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-ead/sead/100)
> math/Matrix: Add comparison operators for Matrix34

- CMakeLists.txt
- include/controller/nin/seadNinJoyNpadDevice.h
- include/controller/seadAccelerometerAddon.h
- include/controller/seadControlDevice.h
- include/controller/seadController.h
- include/controller/seadControllerAddon.h
- include/controller/seadControllerBase.h
- include/controller/seadControllerDefine.h
- include/controller/seadControllerMgr.h
- include/controller/seadControllerWrapper.h
- include/controller/seadControllerWrapperBase.h
- include/controller/seadPatternRumbleAddon.h
- include/framework/seadTaskBase.h
- include/math/seadVector.h
- include/math/seadVector.hpp
- include/math/seadVectorCalcCommon.h
- include/math/seadVectorCalcCommon.hpp
- modules/src/controller/seadController.cpp
- modules/src/controller/seadControllerBase.cpp
- modules/src/controller/seadControllerMgr.cpp
- modules/src/controller/seadControllerWrapper.cpp
- modules/src/controller/seadControllerWrapperBase.cpp
- modules/src/controller/seadPatternRumbleAddon.cpp
This PR adds all files from the recent changes regarding controller stuff from the Wii U decomp repo. All functions are either matching or have been commented as being a mismatch.
In that route, I discovered that `TaskBase` seems to have another function, which is missing so far. As it really exists as a function and is not inlined in Super Mario Odyssey, the definition has to be added to a `cpp` later (when other functions are being implemented), so I just annotated what it should return for the moment.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-ead/sead/102)
> `controller`: Port changes from Wii U decomp repo

- include/prim/seadFormatPrint.h
Removing first declaration of this method, keeping only the full definition with method body a few lines further down.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-ead/sead/104)
> prim/FormatPrint: deduplicate format

- include/prim/seadScopedLock.h
See https://github.com/open-ead/sead/pull/105#pullrequestreview-1064473605
@MonsterDruide1 let me know if this fixes makeScopedLock on Clang 3.9.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-ead/sead/106)
> prim/ScopedLock: Fix makeScopedLock for pre-C++17 builds

- CMakeLists.txt
- include/heap/seadArena.h
- include/heap/seadHeap.h
- include/heap/seadHeapMgr.h
- include/thread/seadThread.h
- modules/src/heap/seadArena.cpp
- modules/src/heap/seadHeapMgr.cpp
Two `NON_MATCHING`s on this one:
1. `HeapMgr::destroy` cleans up two static variables and destroys all heaps from the lists. However, I can't find the right iterator for this one, so I just listed all three versions I tried there. (https://decomp.me/scratch/saxAV)
2. `HeapMgr::findContainHeap` looks a bit too lengthy overall - especially looking at the CriticalSection-mutex. (https://decomp.me/scratch/QPDI8)
Apart from that, I added a few functions to `FindContainHeapCache`, which partly seem useless to me - but I can't keep up the match level with fewer functions, as I don't know enough about how Atomics are used here.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-ead/sead/105)
> heap: Implement seadHeapMgr and seadArena

- CMakeLists.txt
- include/gfx/seadFrameBuffer.h
- modules/src/gfx/seadFrameBuffer.cpp
Function `isDerive` of RTTI doesn't generate for FrameBuffer though.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-ead/sead/119)
> gfx: Implement FrameBuffer and LogicalFrameBuffer

- include/framework/seadGameFrameworkNx.h
This was probably missed when doing the `nvn`-structure rework, as this header file is not referenced anywhere (yet).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-ead/sead/120)
> framework: Fix GameFrameworkNx include

- CMakeLists.txt
- include/devenv/seadFontMgr.h
- include/gfx/seadDrawContext.h
- modules/src/devenv/seadFontMgr.cpp
Final changes from the `SuperMarioOdysseyOnline`-repo.
Missing functions marked in the `cpp`. Along with it, some functions weren't able to match completely:
- `ctor`+`createInstance` on both - Not only a difference in `C1`/`C2`, but also some instruction ordering.
- `begin` on both - Might have something to do with the `pfnc_nvn` reference, have these been tested before?
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-ead/sead/122)
> devenv: Add DebugFontMgr*Nvn

- CMakeLists.txt
- include/gfx/seadDrawLockContext.h
- modules/src/gfx/seadDrawLockContext.cpp
Not much more to say about it. Pretty simple, all functions are matching.
Inspired by
https://github.com/CraftyBoss/SMO-Galaxy-Gravity/blob/master/include/sead/gfx/seadContext.h#L33
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-ead/sead/124)
> gfx: Add `seadDrawLockContext`

- include/gfx/seadCamera.h
With this, all functions about `sead::*Camera` should be defined in the headers.
Inspiration and parts of code from here:
https://github.com/CraftyBoss/SMO-Galaxy-Gravity/blob/master/include/sead/gfx/seadCamera.h
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-ead/sead/123)
> gfx: Add more functions to seadCamera

- include/gfx/seadCamera.h
According to a comment by @aboood40091 , renaming this member of `sead::DirectCamera`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-ead/sead/126)
> gfx/seadCamera: Rename DirectCamera member

- CMakeLists.txt
- include/framework/seadTask.h
Added a header for sead::Task.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-ead/sead/130)
> framework: Add sead::Task header

- include/math/seadMathCalcCommon.hpp
- include/math/seadQuatCalcCommon.h
- include/math/seadQuatCalcCommon.hpp
- include/math/seadVectorCalcCommon.h
- include/math/seadVectorCalcCommon.hpp
MathCalcCommon::max was changed due to being the exact same implementation as ::clampMin, which is unnecessary, and the new implementation was needed. QuatCalcCommon::setAxisAngle converts and axis and an angle into a quaternion, and a new Vector3CalcCommon::rotate was added for quaternion rotation on a vector. the implementation is matching in some functions, but has a register swap mismatch in others. it's as good as its gonna get for now.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-ead/sead/132)
> CalcCommon additions, minor fixes

- include/math/seadVector.hpp
- include/math/seadVectorCalcCommon.hpp
This changes set() to rely on the BaseVec3 copy assignment operator rather than set x, y, z manually. Vector3's operator= seems to do the latter so it has been adjusted to not use set().
Everything in BotW still matches after this change, and this should let us get rid of a few ugly usages of `.e`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-ead/sead/135)
> Vector3: implement set() in a different way

- include/container/seadTList.h
As discussed in Discord, we might want to change those two functions to be consistent with the `pushFront` and `pushBack`-functions above. I did not notice any regressions in `smo` or `botw` with this change.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-ead/sead/136)
> container/TList: Change mList of node during insert

- include/filedevice/nin/seadNinFileDeviceBaseNin.h
- modules/src/filedevice/nin/seadNinFileDeviceBaseNin.cpp
- modules/src/filedevice/nin/seadNinSaveFileDeviceNin.cpp
- modules/src/filedevice/seadFileDeviceMgr.cpp
Adjusts the path of changed files/members to allow compiling again.
Should be merged along with https://github.com/open-ead/nnheaders/pull/27.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-ead/sead/133)
> Adjust with `nnheaders` - `#27`

- include/heap/seadHeapMgr.h
This PR adds needed changes for SMO HeapUtil functions.
https://github.com/Fuzzy2319/OdysseyDecomp/blob/HeapUtil/lib/al/src/Library/Memory/HeapUtil.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-ead/sead/138)
> HeapMgr minor changes

- include/math/seadVectorFwd.h
There seems to be another, very rarely used variant of the `sead::Vector` type, containing an `uint`/`u32` as elements.
In SMO, it can be observed in a bunch of `al::KCollisionServer` symbols, along with `al::Dynamic{Mesh, DrawActor, MeshDrawer}`. There also seems to be a single occurence in `agl::detail::SMAAResTextureGenerator::calcSearchEdgeFromKey`.
I can confirm that at least the `Vector3u` and `Vector4u` variants exist, I didn't find an occurence of `Vector2u` though - I find it very likely to exist as well though.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-ead/sead/137)
> math: Add `u32` variant to `Vector`s

- include/math/seadVector.hpp
- include/math/seadVectorCalcCommon.hpp
- modules/src/controller/seadControllerBase.cpp
- modules/src/controller/seadControllerWrapper.cpp
https://github.com/open-ead/sead/pull/135 adjusted it for Vector3, this will change it for Vector2 and Vector4 accordingly.
Two mismatches popped up across the whole `SMO` project, which are the two other files changed here: `sead::Controller` stuff, where I used `.set()` for some reason. Changing those to `=` assignments gets them matching again.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-ead/sead/139)
> math/seadVector: Adjust Vector2/4::set according to Vector3

- include/math/seadVector.h
- include/math/seadVector.hpp
- include/math/seadVectorCalcCommon.h
- include/math/seadVectorCalcCommon.hpp
Implementing a few more functions for `Vector2` that might be helpful in some places, for example when reading/processing controller (stick) input data.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-ead/sead/140)
> math/seadVector2: Implement dot, cross, squaredLength

- include/framework/nx/seadGameFrameworkNx.h
SMO's `al::GameFrameworkNx` requires the `sead` one to have the correct size. Besides filling the struct with the correct size, I also added some names and types based on @MonsterDruide1 's struct
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-ead/sead/141)
> GameFrameworkNx: Add member variables

- include/math/seadQuatCalcCommon.h
- include/math/seadQuatCalcCommon.hpp
This is the last PR of a series of PRs across all libraries, which will try to fix more issues with the current headers by introducing a new workflow on the `OdysseyDecomp` repo. As of right now, trying to compile certain combinations of headers or singular headers individually will fail, due to a number of reasons: Duplicate definitions, stubs that should have been replaced by including their proper definition, includes missing altogether and maybe more.
For this repo, only two includes were missing: `seadQuatCalcCommon.h` makes use of the `f32` type in `slerpTo` without previously defining it, so it should include `basis/seadTypes.h`. The implementation `.hpp` file uses `VectorCalcCommon` in `makeVectorRotation`, so it should include `math/seadVectorCalcCommon.h` as well.
- - -
This …
> math/seadQuatCalc: Add missing includes

- include/devenv/seadEnvUtil.h
Needed by https://github.com/zeldaret/botw/pull/130
`LayoutResourceMgr` use the enum names to get the font files, so I am pretty sure the names are correct
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-ead/sead/143)
> Add `sead::RegionID` and `sead::EnvUtil::getRegion` declarations

- include/math/seadQuat.h
It seems like `seadQuat`s prefer to be set in order of how they store their members, being `xyzw`. This PR fixes matching on `agl::utl::Parameter<sead::Quatf>::clone()` on both SMO and BotW, and does not introduce any regressions on both projects.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-ead/sead/144)
> math/seadQuat: Adjust `operator=` to follow memory order

- .github/workflows/lint_pr.yml
Fixes problems with python not finding `strtobool`, which caused linting to fail before.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-ead/sead/145)
> lint: Update `clang-format-lint-action` to `v0.17`

- include/framework/nx/seadGameFrameworkNx.h
Apparently, the class declarations of `nn` have ended up within `sead` here. This is not only simply wrong, but also causes problems when trying to compile this file in combination with proper `nn::` usages, as those cannot be located, as the compiler assumes they should be under `nn::sead` then.
This issue can be fixed/corrected by moving the `nn` namespace here to outside of `sead`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-ead/sead/146)
> framework/nx: Fix `nn` namespace in `GameFrameworkNx`

- include/math/seadQuat.h
- include/math/seadQuat.hpp
- include/math/seadQuatCalcCommon.h
- include/math/seadQuatCalcCommon.hpp
Here, a new `set(const Quat&)` is added similar to the `set` functions in `Vector`s.
Here is an example of this function being used:
https://decomp.me/scratch/DMDBE
(weird casting to `Base` can be omitted by using `set` instead)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-ead/sead/148)
> math/seadQuat: Implement `set(const Quat&)`-operator

- include/gfx/seadCamera.h
From Super Mario Odyssey:
`al::CameraInterpole` contains four `sead::LookAtCamera`s. During its destructor, these need to be destructed as well. Here, the destructor contains `sead::Camera::~Camera()` instead - which means that the destructor of `LookAtCamera` has been inlined, and thus must have been header-defined.
It can be written as
- `~LookAtCamera() override = default;`
- `~LookAtCamera() override {}`
... but I think the first option is preferred here - please correct me if the other option should've been used.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-ead/sead/149)
> gfx/LookAtCamera: Default Destructor

- include/framework/seadTask.h
This fixes some warnings `overrides a member function but is not marked 'override'`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-ead/sead/151)
> framework: Use SEAD_RTTI_OVERRIDE macro

- include/math/seadVector.h
- include/math/seadVector.hpp
- include/math/seadVectorCalcCommon.hpp
Fixes a mismatch by changing the equation order and allows to be used within the vector.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-ead/sead/156)
> math: Fix `Vector3::rotate(const Quat&)`

- include/math/seadQuatCalcCommon.hpp
The current implementation of `setRPY` mismatches on some functions in SMO, specifically `al::getQuat(sead::Quatf*, const al::PlacementInfo&)`, where the order of stores is being switched around by the compiler - which is apparently not possible with the current implementation. Changing this to the code suggested in this PR solves those mismatches, and does not introduce any new mismatches across SMO.
This change has not been tested with BotW (yet).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-ead/sead/152)
> math/Quat: Fix `setRPY`

- include/math/seadMatrixCalcCommon.hpp
Change this implementation to look similar to the one of `makeRT`, pre-calculating some of the re-usable sin/cos products. This change allows `al::tryGetMatrixTRS(sead::Matrix34f*, const al::PlacementInfo&)` to match, and as it has not been used anywhere else so far, does not introduce regressions in SMO.
This has not been tested with BotW (yet).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-ead/sead/153)
> math/Matrix: Fix `makeSRT`

- include/prim/seadDelegate.h
this type was deprecated in c++17 and removed in c++20, as far as i know this `std::invoke_result_t` should be equivalent.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-ead/sead/157)
> remove deprecated `std::result_of_t`

- include/controller/seadControllerBase.h
- include/prim/seadDelegate.h
in odyssey (and i think in 3DW/3DL as well), the `al::ReplayController` class, which derives from `sead::ControllerBase`, modifies `mPadTrig`, `mPadHold`, `mLeftStick` and `mPointer`, as can be seen [here](https://github.com/tetraxile/OdysseyDecomp/blob/0b9c2ceebeabb6c095b8d5ab76ee3ce0cd231b78/lib/al/Library/Controller/ReplayController.cpp#L56).
unsure if it's the best way to handle it to just make everything `protected` for this class, but `mPointer` is way down the bottom of the class so it'd be pretty messy to only make some `private` and some `protected`. also may be a bit excessive to add `protected` setters for everything. i think this is the cleanest way to handle it, hopefully it doesn't break something else.
also sorry for the messy commit history here i accidentally did my …
> `ControllerBase`: change member variables to `protected`

- include/prim/seadDelegate.h
as mentioned in #157, there were indeed some compilation issues resulting from this: `OdysseyDecomp` uses `c++1z`, which doesn't yet have `std::invoke_result_t`. to get around this i just added some preprocessor `#if`s to check that the standard version is below `c++20`, in which case it will just use `std::result_of_t` as it did before.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-ead/sead/164)
> prim/LambdaDelegate: Check standard version for `std::invoke_result_t`

- include/container/seadStrTreeMap.h
As specified by #118, and required by https://github.com/MonsterDruide1/OdysseyDecomp/pull/442, the destructor of `StrTreeMap` should be removed. This PR closely follows what has been done to `TreeMap` in https://github.com/open-ead/sead/commit/eadee1e89cee0065c767bbe8963d4630b9b424ee.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-ead/sead/169)
> container: Remove `StrTreeMap`-destructor

- include/math/seadVector.h
- include/math/seadVector.hpp
Required for matching some functions within `Library/LiveActor/ActorMovementFunction.cpp` in SMO. Even manually calling `sead::Vector3CalcCommon<f32>::sub` did cause a mismatch with one example, which got resolved when using this newly introduced `setSub` instead.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-ead/sead/173)
> math: Add `Vector3::setSub`

- include/container/seadStrTreeMap.h
- include/container/seadTreeMap.h
As required by `BirdPlayerGlideCtrl::init` in https://github.com/MonsterDruide1/OdysseyDecomp/pull/442, this allocation function should cache the `sizeof` before going into the allocation or failure branches. The current implementation mismatches there.
Only `StrTreeMap` is required to be fixed for that PR, but as `TreeMap` is very similar with its implementation, it probably makes sense to change it there accordingly.
This change has been tested in SMO and BotW and does not introduce any mismatches in either project.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-ead/sead/175)
> container: Fix `allocBuffer` in `[Str]TreeMap`

- include/container/seadRingBuffer.h
This function wasn't implemented properly and caused a mismatch. None of the repositories make use of it at the moment but is required to match HackFork::updateInput
The new implementation is from looking at other ring buffer implementations of open source projects.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-ead/sead/177)
> container: Fix RingBuffer::forcePushBack

- include/math/seadVector.h
- include/math/seadVector.hpp
Helps in matching some functions within `Library/LiveActor/ActorMovementFunction.cpp` in SMO. Manually calling `sead::Vector3CalcCommon<f32>::multScalar` or doing a dimension-wise multiplication also resulted in a match for all usages, but I adding a function like this would make things easier/shorter to match.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-ead/sead/174)
> math: Add `Vector3::setScale`

- include/container/seadStrTreeMap.h
- include/container/seadTreeMap.h
Implementation as required by https://github.com/MonsterDruide1/OdysseyDecomp/pull/442.
It is possible to remove the `Value* ptr` variable and put immediate returns everywhere, but I think this one is a bit nicer. Switching the `mSize < mCapacity` to `mSize >= mCapacity` causes a mismatch, and removing the final `else` while using early returns also mismatches.
This change has been tested with SMO and BotW and does not introduce any new mismatches - BotW apparently checks some `TreeMap::insert` already, but it is unaffected by this change.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-ead/sead/176)
> container: Fix `insert` in `[Str]TreeMap`

- include/controller/seadController.h
- include/controller/seadControllerMgr.h
As reported by @tetraxile, our current implementation throws errors when trying to use any of the templated functions using `DynamicCast` - because the compiler struggles to understand that `::type` is a type and not a variable here. By adding `typename` there, this is fixed.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-ead/sead/179)
> Controller: Fix usages of `DynamicCast`

- include/math/seadVector.h
- include/math/seadVector.hpp
- include/math/seadVectorCalcCommon.h
- include/math/seadVectorCalcCommon.hpp
I can't believe normalize and length didn't exist yet. ~~`al::calcLongitudeLatitudeFromDir` uses Vector2f math so I need these to implement the function properly.~~
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-ead/sead/185)
> Math: Add normalize and length support for Vector4 types

- include/controller/seadController.h
classes that inherit from this one need to set their `mId`, e.g. `al::NpadController`'s ctor in SMO.
could make this a setter if necessary but i think it makes sense to just be protected.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-ead/sead/184)
> `controller`: make `Controller::mId` protected

- include/math/seadVectorCalcCommon.hpp
Found by @Tomoeko this somehow still matches perfectly with the 5 instances of this function and fixes `al::rotateQuatLocalDirDegree` see https://decomp.me/scratch/pVSzv
I feel pretty confident that this is the true and final form of this function as both operations are exactly the same as seen more clearly with some additional spacing for the missing fields
```
Quat r;  // quat-multiplication with 0 on w for v
r.x =                (q.y * v.z) - (q.z * v.y) + (q.w * v.x);
r.y = -(q.x * v.z) +               (q.z * v.x) + (q.w * v.y);
r.z =  (q.x * v.y) - (q.y * v.x)               + (q.w * v.z);
r.w = -(q.x * v.x) - (q.y * v.y) - (q.z * v.z);
// quat-multiplication with zero on o.w and everything is negated
o.x =  (r.x * q.w) - (r.y * q.z) + (r.z * q.y) - (r.w * q.x);
o.y =  (r.x * q.z) + …
```
> Math: Fix Vector3::Rotate attempt 2

- include/prim/seadStorageFor.h
As the two `construct`-methods (`construct()` and `constructDefault()`) call `operator new`, the correct implementation should be provided here, by including `seadNew.h`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-ead/sead/171)
> prim: Add missing include in `StorageFor`

- include/math/seadVector.h
Often, the pattern of first allocating a vector, then immediately assigning it to be a cross product can be observed.
With this change, the following two code snippets are equivalent:
```cpp
// old:
Vector3 result;
result->setCross(a, b);
// new:
Vector3 result = a.cross(b);
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-ead/sead/190)
> math: Add `Vector3::cross`

- README.md
In PR #164, we determined that the `README` should be adjusted to better reflect the compiler compatibility of this project.
We cannot fully go down to `C++14`, because there are way more features we use from `C++1z`: `constexpr`, `inline` variables, nested `namespace nn::oe`, which already at least cause warnings when compiled with `C++14`. But most importantly, causing actual errors: `is_always_lock_free` on `std::atomic`, which has been introduced by `C++17` (<https://en.cppreference.com/w/cpp/atomic/atomic/is_always_lock_free>) ; and `std::size`, also `C++17`-only (<https://en.cppreference.com/w/cpp/iterator/size>).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-ead/sead/168)
> README: Adjust compiler compatibility note

- include/prim/seadSafeString.h
I don't know what to say but I need an unsafe version of cstr() because is required by al::ParameterObj::findParameter in SMO. Which I find in my opinion unusual to use a safe string and end up using non safe operations.
https://decomp.me/scratch/2yjeN
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-ead/sead/191)
> prim: Add unsafeCstr to SafeStringBase

- CMakeLists.txt
- include/resource/seadParallelSZSDecompressor.h
Variant of `SZSDecompressor` that is able to run in the background (using a separate `sead::Thread`). Needed by `al::SystemKit` in SMO, which (determined by the parameters given to the function) either constructs a `ParallelSZSDecompressor` or `SZSDecompressor`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-ead/sead/195)
> resource: Add header of `ParallelSZSDecompressor`

- include/math/seadVector.h
- include/math/seadVector.hpp
Pretty straight-forward - another function of this pattern is needed, apparently. The exact operation in question here is more like `setScaleAdd`, but has the two operands of the addition flipped - but it also matches when using `setAdd` and pre-scaling one of the arguments.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-ead/sead/197)
> math: Add `Vector3::setAdd`

- include/math/seadMatrixCalcCommon.hpp
These two variables are not needed by the computations below, so the compiler (rightfully) complains that these are not used afterwards. They can either be commented out (as done in this PR), or removed - please tell me if removing them entirely is preferred.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-ead/sead/198)
> math: Fix `-Wunused-variable` in `seadMatrixCalcCommon.hpp`

- include/gfx/seadCamera.h
- include/heap/seadHeapMgr.h
- modules/src/gfx/seadCamera.cpp
- modules/src/heap/seadHeapMgr.cpp
While developing a new version of `viking` that uses a new file list format instead of the function csv, I noticed that some `sead` related symbols that aren't marked as weak in the 1.0 smo executable were marked as weak in the decomp elf. When using clang, if a function is a **header defined** virtual, it always gets weak linkage (marked with `W` when using `llvm-nm`) but these functions are marked with `T` in the smo executable, which means they were placed into the cpp by the devs. For this reason I've moved them there which also matches some `sead` RTTI related functions in these classes
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-ead/sead/200)
> Move some incorrectly placed empty virtual dtors into cpp

- include/container/seadPtrArray.h
- modules/src/heap/seadHeapMgr.cpp
This pull request changes `sead::PtrArrayImpl::popBack` to match SMO.
Notes:
* The `popBack` method is inlined, so there’s nothing to match with _directly_.
* This PR fixes `sead::HeapMgr::destroy` which was previous mismatching.
* This PR is a prerequisite for matching `PlayerBindableSensorList` (see [OdysseyDecomp#181](https://github.com/MonsterDruide1/OdysseyDecomp/pull/181)) which uses the `popBack` method.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-ead/sead/203)
> container: Fix `PtrArrayImpl::popBack`

- include/math/seadBoundBox.h
- include/math/seadBoundBox.hpp
This function is used by `CollisionDirector::checkStrikeArrow` within SMO. It accepts a point and (if necessary) adjusts the `mMin` and `mMax` of the `BoundBox`, so it includes this point as well. In the aforementioned function, it is called twice to set up a previously uninitialized BoundBox - this codegen cannot be reproduced with existing functions. The function name is totally made-up, so I'm happy to take suggestions on that as well.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-ead/sead/204)
> math: Implement `BoundBox::setIncludePoint`

- include/container/seadStrTreeMap.h
Required to match `al::ActorResourceHolder::ActorResourceHolder(int)` in SMO.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-ead/sead/206)
> container: Early-abort on failed `StrTreeMap::allocBuffer`

- include/prim/seadSafeString.h
Here, I'm adding the same two overrides for `WFixedSafeString` as already exist for `FixedSafeString`. At least the bottom one needs to exist, as the associated symbol listed in SMO cannot be generated otherwise. I do not have any proof/indication that the first (non-virtual function) exists, but I added it anyways for consistency with other `sead::SafeString`-types.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-ead/sead/209)
> prim/SafeString: Add `WFixedSafeString::operator=`

- include/time/seadTickSpan.h
- include/time/seadTickTime.h
- modules/src/thread/nin/seadEventNin.cpp
- modules/src/thread/nin/seadThreadNin.cpp
- modules/src/time/seadTickSpan.cpp
Required after merging https://github.com/open-ead/nnheaders/pull/48
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-ead/sead/211)
> NintendoSDK: Update `nn::os::Tick` to struct

- CMakeLists.txt
- include/framework/seadTaskBase.h
- include/framework/seadTaskID.h
- modules/src/framework/seadTaskBase.cpp
Mostly done by specifying some default members of the class.
Other than that, the type of `TaskClassID::Type` has been changed from `u64` to `u32` to match the instructions accessing it.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-ead/sead/212)
> framework: Implement `TaskBase::CreateArg`

- include/math/seadVector.h
- include/math/seadVector.hpp
Similar to what `Vector3::setAdd` already implements. Results in slightly less optimal codegen (ldr, add, str ; ldr, add, str), which is sometimes desired to match a function.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-ead/sead/218)
> math: Add `Vector2::setAdd`
